# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YuanZShi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YuanZShi
pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'YYModel'
  target 'YuanZShiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YuanZShiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
